apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.app.sql}}"
  labels:
    app: "{{.Values.app.name}}"
spec:
  ports:
    - port: 3306
  selector:
    app: "{{.Values.app.name}}"
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: "{{.Values.app.name}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.app.sql}}"
  labels:
    app: "{{.Values.app.name}}"
spec:
  selector:
    matchLabels:
      app: "{{.Values.app.name}}"
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{.Values.app.name}}"
        tier: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{.Values.secret.name}}"
              key: rootPassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: "{{.Values.secret.name}}"
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: "{{.Values.secret.name}}"
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{.Values.secret.name}}"
              key: password

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
