apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.service.name}}"
  labels:
    name: "{{.Values.service.name}}"
    app: "{{.Values.app.name}}"
spec:
  type: NodePort
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
  selector:
    app: "{{.Values.app.name}}"
    name: "{{.Values.app.pod}}"