version: '3.2'
services:
  org-hierarchy:
    image: org-hierarchy:latest
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: kube
   
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fileDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    